### ISSUE TITLE
broken pipe error

### ISSUE THREAD

**Issue by saheethas** [urld/passmgr#2]
Hi,

I installed this Password manager tool. But I'm unable to read the passphrase from the command line for my selected entries. It's reporting a broken pipe message as below:

```
#  passmgr
[passmgr] master passphrase for /root/.passmgr_store: 

n)   User                   URL
1)   Saheetha               linoxide.com
2)   sshameer@example.com   work.example.com
3)   testuser               website.com
4)   test                   test.com

Choose a command [(S)elect/(f)ilter/(a)dd/(d)elete/(q)uit] S
Select: 1

Passphrase copied to clipboard!
Clipboard will be erased in 15 seconds.

write |1: broken pipe
```

Can you please help me on how to sort this problem?

**Comment by urld** [comment]
Do you have the xclip or xsel command installed if you try to run passmgr on a linux system?

**Comment by Linoxide** [comment]
Hey.. Thanks for getting back. Here we have. replying for saheethas

```
[root@centos ~]# xsel --version
xsel version 1.2.0 by Conrad Parker <conrad@vergenet.net>
[root@centos ~]# xclip -version
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[root@centos ~]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@centos ~]# uname -ar
Linux centos 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@centos ~]#
```

Let me know if you want us to check any log file or try any commands

**Comment by urld** [comment]
Could you try to verify, if xclip and xsel are working correctly?
```
echo "xsel test" | xsel --input --clipboard

echo "xclip test" | xclip -in -selection clipboard
```
After each command the echoed text should be in your clipboard.

Could it be the case that you try to run passmgr inside an containerized environment (e.g. docker)?

If this is the case it is possible that xclip or xsel are not working like you would expect since the actual clipboard is part of the window system X11, which is not accessible by default from within a container.

**Comment by Linoxide** [comment]
```
[root@centos ~]# echo "xsel test" | xsel --input --clipboard
xsel: Can't open display: (null)
: Inappropriate ioctl for device
[root@centos ~]# echo "xclip test" | xclip -in -selection clipboard
Error: Can't open display: (null)
```
We are not using container. Just from terminal. You thing we need try from GUI Terminal ?

**Comment by Linoxide** [comment]
running X11 in production is risk :-(

**Comment by urld** [comment]
Unfortunately you need some sort of clipboard functionality. Currently this is provided by X11.
Maybe there is similar functionality in tmux or screen which can be used, but I haven't looked into it.

In the meanwhile you could work around this issue by running passmgr locally and use your local clipboard to paste passwords into your remote terminal if your environment allows that.
